(function () {
  'use strict';
  const M=window.ComexModel,state=M.seed(),content=document.getElementById('content'),modal=document.getElementById('modal');
  let route='history',selectedPO='',tab='overview',selectedEmail='MAIL-SEED',q='',statusFilter='',wizard=null,wizardStep=0,wizardError='',successOrders=[];
  const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const USD=n=>n===null||n===undefined?'Pendiente':new Intl.NumberFormat('es-CL',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(n);
  const CLP=n=>n===null||n===undefined?'Pendiente':new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
  const NUM=n=>new Intl.NumberFormat('es-CL',{maximumFractionDigits:3}).format(n);
  const DATE=x=>x?new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(x+'T12:00:00Z')):'Por confirmar';
  const TIME=x=>new Intl.DateTimeFormat('es-CL',{hour:'2-digit',minute:'2-digit',timeZone:'America/Santiago'}).format(new Date(x));
  const poById=id=>state.orders.find(p=>p.id===id);
  const tone=s=>['Gerencia','Gerencia general','Preparación','Por vincular'].includes(s)?'amber':['Rechazada'].includes(s)?'red':['Finalizada','Procesado','Enviada a fábrica'].includes(s)?'teal':'blue';
  const pill=(s,t)=>'<span class="pill '+(t||tone(s))+'">'+E(s)+'</span>';
  const button=(label,action,id='',cls='secondary',extra='')=>'<button class="'+cls+'" data-action="'+action+'" '+(id?'data-id="'+E(id)+'"':'')+' '+extra+'>'+label+'</button>';
  const linkPO=id=>'<button class="po-link" data-action="po" data-id="'+E(id)+'">'+E(id)+'</button>';
  const navItems=[['history','▤','Historial de PO'],['request','＋','Nueva solicitud'],['approvals','✓','Aprobaciones'],['emails','✉','Correos procesados'],['factory','▥','Fábrica'],['customs','▣','Aduanas'],['transport','▱','Transporte'],['costs','$','Costos'],['masters','⌘','Maestros']];
  const headings={history:'Historial de PO',request:'Nueva solicitud',approvals:'Aprobaciones',emails:'Correos procesados',factory:'Fábrica',customs:'Aduanas',transport:'Transporte',costs:'Costos',masters:'Maestros',alerts:'Alertas',po:'Expediente de PO'};
  function toast(text){const box=document.getElementById('toast');box.textContent=text;box.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.classList.remove('visible'),4000);}
  function head(title,subtitle='',actions=''){return '<div class="page-head"><div><p class="eyebrow">COMEX / OPERACIÓN</p><h1>'+title+'</h1><p>'+subtitle+'</p></div><div class="button-row">'+actions+'</div></div>';}
  function panel(title,body,action=''){return '<section class="panel"><div class="panel-head"><h2>'+title+'</h2>'+action+'</div><div class="panel-body">'+body+'</div></section>';}
  function empty(title,text){return '<div class="empty"><h3>'+title+'</h3><p>'+text+'</p></div>';}
  function showDialog(title,body,foot=''){document.getElementById('modal-body').innerHTML='<div class="modal-head"><h2 id="modal-title">'+title+'</h2>'+button('×','close','','icon-button','aria-label="Cerrar"')+'</div><div class="modal-content">'+body+'</div><div class="modal-foot">'+(foot||button('Cerrar','close'))+'</div>';if(!modal.open)modal.showModal();}
  function close(){modal.close();}
  function go(next,id='',nextTab='overview'){location.hash=next==='po'?'po/'+id+'/'+nextTab:next;if(route===next&&selectedPO===id){tab=nextTab;render();}}
  function routeChanged(){const parts=location.hash.slice(1).split('/');route=headings[parts[0]]?parts[0]:'history';selectedPO=parts[1]||'';tab=parts[2]||'overview';if(route==='request'&&!wizard)initWizard();render();document.getElementById('sidebar').classList.remove('open');document.getElementById('menuToggle').setAttribute('aria-expanded','false');window.scrollTo(0,0);}
  function render(){
    const pending=state.orders.filter(p=>['Gerencia','Gerencia general'].includes(p.status)).length;
    document.getElementById('navigation').innerHTML=navItems.map(([key,icon,label],i)=>(i===8?'<div class="nav-divider"></div>':'')+'<a class="nav-item '+(route===key?'active':'')+'" href="#'+key+'" '+(route===key?'aria-current="page"':'')+'><span class="nav-icon" aria-hidden="true">'+icon+'</span>'+label+(key==='approvals'&&pending?'<span class="nav-count">'+pending+'</span>':'')+(key==='emails'&&state.emails.some(m=>m.status==='Por vincular')?'<span class="nav-count">!</span>':'')+'</a>').join('');
    document.getElementById('breadcrumb').textContent=headings[route];document.getElementById('alertCount').textContent=M.alerts(state).length;
    const views={history:historyView,request:wizardView,approvals:approvalView,emails:emailView,factory:factoryView,customs:customsView,transport:transportView,costs:costView,masters:masterView,alerts:alertView,po:detailView};content.innerHTML=(views[route]||historyView)();
    document.title=(route==='po'?selectedPO:headings[route])+' · COMEX';
  }
  function historyRows(){const rows=state.orders.filter(p=>(!statusFilter||p.status===statusFilter)&&(!q||[p.id,p.client,p.factory,p.engineer,...p.lines.map(l=>l.name)].join(' ').toLowerCase().includes(q.toLowerCase())));return '<table><thead><tr><th>PO / RESPONSABLE</th><th>PRODUCTOS / FÁBRICA</th><th>ESTADO</th><th>AVANCE</th><th>ETA</th><th>MERCADERÍA USD</th><th></th></tr></thead><tbody>'+rows.map(p=>'<tr><td>'+linkPO(p.id)+'<span class="cell-sub">'+E(p.engineer)+' · Rev. '+p.revision+'</span></td><td>'+E(p.lines[0].name)+(p.lines.length>1?' <span class="muted">+'+(p.lines.length-1)+'</span>':'')+'<span class="cell-sub">'+E(p.factory)+'</span></td><td>'+pill(p.status)+'</td><td><div class="progress-wrap"><div class="progress-track"><i style="width:'+M.progress(p)+'%"></i></div><span class="progress-num">'+M.progress(p)+'%</span></div></td><td class="numeric">'+DATE(p.eta)+'<span class="cell-sub">Requerida: '+DATE(p.requested)+'</span></td><td class="numeric">'+USD(M.total(p))+'</td><td>'+button('Abrir','po',p.id,'text-button')+'</td></tr>').join('')+'</tbody></table>'+(!rows.length?empty('Sin coincidencias','Cambia la búsqueda o el filtro de estado.'):'');}
  function historyView(){const count=state.orders.length,pending=state.orders.filter(p=>['Gerencia','Gerencia general'].includes(p.status)).length,inTransit=state.orders.filter(p=>p.status==='En tránsito').length,docs=state.orders.reduce((n,p)=>n+p.docs.length,0);return head('Historial de PO','Cada orden, sus documentos y su avance en un mismo lugar.',button('＋ Nueva solicitud','new','','primary'))+'<div class="stats">'+[[count,'Órdenes de compra','Una PO por embarque'],[pending,'Por aprobar','Gerencia / Gerencia general'],[inTransit,'En tránsito','Seguimiento por expediente'],[docs,'Documentos archivados','Clasificados por etapa']].map(([v,label,note],i)=>'<div class="stat"><div class="stat-label">'+label+'<span aria-hidden="true">'+['▤','✓','▱','▣'][i]+'</span></div><div class="stat-value '+(i===3?'stat-accent':'')+'">'+v+'</div><div class="stat-note">'+note+'</div></div>').join('')+'</div><section class="panel"><div class="panel-head"><h2>Órdenes de compra</h2>'+button('Exportar historial','export-history','','text-button')+'</div><div class="toolbar"><div class="search"><span aria-hidden="true">⌕</span><input id="historySearch" aria-label="Buscar PO, producto o responsable" placeholder="Buscar PO, producto o responsable" value="'+E(q)+'"></div><select id="statusFilter" aria-label="Filtrar por estado"><option value="">Todos los estados</option>'+[...M.stages,'Rechazada'].map(s=>'<option '+(s===statusFilter?'selected':'')+'>'+E(s)+'</option>').join('')+'</select><span class="result-count">'+count+' PO en esta sesión</span></div><div id="historyTable" class="table-scroll">'+historyRows()+'</div></section><div class="info-box neutral">El avance representa hitos del proceso. Abre una PO para consultar sus fechas, documentos, costos e historial de eventos.</div>';}
  function initWizard(po){wizard=po?{engineer:po.engineer,client:po.client,destination:po.destination,requested:po.requested,shipments:1,lines:po.lines.map(l=>({product:l.product,qty:l.qty})),revisionPO:po.id}:{engineer:'Ingeniería A',client:'Cliente Norte · ejemplo',destination:'Destino del cliente · ejemplo',requested:'2026-11-10',shipments:1,lines:[{product:'P100',qty:12000}],revisionPO:null};wizardStep=0;wizardError='';successOrders=[];}
  function wizardTotal(){return wizard.lines.reduce((n,l)=>n+(state.products.find(p=>p.id===l.product)?.price||0)*Number(l.qty||0),0);}
  function collectWizard(){document.querySelectorAll('[data-wfield]').forEach(el=>wizard[el.dataset.wfield]=el.value);document.querySelectorAll('[data-line-product]').forEach(el=>wizard.lines[Number(el.dataset.lineProduct)].product=el.value);document.querySelectorAll('[data-line-qty]').forEach(el=>wizard.lines[Number(el.dataset.lineQty)].qty=Number(el.value));}
  function productTable(po){return '<div class="table-scroll"><table><thead><tr><th>PRODUCTO</th><th>CANTIDAD KG</th><th>PRECIO UNITARIO USD</th><th>IMPORTE USD</th></tr></thead><tbody>'+po.lines.map(l=>'<tr><td>'+E(l.name||state.products.find(p=>p.id===l.product)?.name||l.product)+'</td><td class="numeric">'+NUM(l.qty)+'</td><td class="numeric">'+USD(l.price??state.products.find(p=>p.id===l.product)?.price)+'</td><td class="numeric">'+USD(l.qty*(l.price??(state.products.find(p=>p.id===l.product)?.price||0)))+'</td></tr>').join('')+'</tbody></table></div>';}
  function wizardView(){
    if(successOrders.length)return '<div class="success"><div class="success-mark">✓</div><p class="eyebrow">SOLICITUD REGISTRADA</p><h1>'+ (wizard?.revisionPO?'Corrección enviada':'Tu solicitud ya tiene PO')+'</h1><p class="muted">Se crearon los expedientes y se solicitó la primera aprobación de demostración.</p>'+successOrders.map(p=>'<div class="new-po-card"><div>'+linkPO(p.id)+'<span class="cell-sub">'+NUM(p.lines.reduce((n,l)=>n+l.qty,0))+' kg · '+USD(M.total(p))+'</span></div>'+pill(p.status)+'</div>').join('')+'<div class="info-box neutral" style="margin-top:22px">Circuito referencial: Gerencia y después Gerencia general. Destinatarios y reglas finales pendientes de confirmación.</div><div class="button-row">'+button('Ver aprobaciones','nav','approvals','primary')+button('Volver al historial','nav','history')+'</div></div>';
    if(!wizard)initWizard();
    const stepNames=['Productos','Entrega','Revisar y enviar'];
    let body='';
    if(wizardStep===0){body='<h2>¿Qué necesitas solicitar?</h2><p class="muted small">Selecciona productos de una misma fábrica. Los precios provienen del maestro aprobado de ejemplo.</p>'+wizard.lines.map((l,i)=>'<div class="product-row"><div class="product-select"><label for="product-'+i+'">Producto</label><select id="product-'+i+'" data-line-product="'+i+'">'+state.products.map(p=>'<option value="'+p.id+'" '+(l.product===p.id?'selected':'')+' '+(!p.approved?'disabled':'')+'>'+E(p.name)+' · '+E(p.factory.replace(' · ejemplo',''))+(!p.approved?' · sin aprobación':'')+'</option>').join('')+'</select></div><div><label for="qty-'+i+'">Cantidad (kg)</label><input id="qty-'+i+'" type="number" min="0.001" step="0.001" max="10000000" data-line-qty="'+i+'" value="'+E(l.qty)+'"></div><div><label>Precio unitario USD</label><div class="product-price">'+USD(state.products.find(p=>p.id===l.product)?.price)+'</div></div>'+button('×','remove-line',String(i),'icon-button','aria-label="Eliminar producto '+(i+1)+'" '+(wizard.lines.length===1?'disabled':''))+'</div>').join('')+'<div class="product-total">'+button('＋ Agregar producto','add-line','','text-button')+'<span>Total referencial <strong>'+USD(wizardTotal())+'</strong></span></div>';}
    if(wizardStep===1){body='<h2>Responsable y entrega</h2><div class="field-grid"><div class="field"><label for="engineer">Ingeniero responsable</label><select id="engineer" data-wfield="engineer">'+['Ingeniería A','Ingeniería B','Ingeniería C'].map(v=>'<option '+(v===wizard.engineer?'selected':'')+'>'+v+'</option>').join('')+'</select></div><div class="field"><label for="client">Cliente</label><select id="client" data-wfield="client">'+['Cliente Norte · ejemplo','Cliente Sur · ejemplo','Cliente Centro · ejemplo'].map(v=>'<option '+(v===wizard.client?'selected':'')+'>'+v+'</option>').join('')+'</select></div><div class="field"><label for="requested">Fecha requerida</label><input id="requested" type="date" min="'+M.DAY+'" data-wfield="requested" value="'+E(wizard.requested)+'"></div><div class="field"><label for="shipments">Embarques solicitados</label><select id="shipments" data-wfield="shipments" '+(wizard.revisionPO?'disabled':'')+'><option value="1" '+(Number(wizard.shipments)===1?'selected':'')+'>1 embarque · 1 PO</option><option value="2" '+(Number(wizard.shipments)===2?'selected':'')+'>2 embarques · 2 PO</option></select></div><div class="field wide"><label for="destination">Destino de entrega</label><input id="destination" maxlength="200" data-wfield="destination" value="'+E(wizard.destination)+'"></div></div><div class="info-box neutral">Una PO por embarque es el supuesto de este prototipo. Para dos embarques, el ejemplo reparte las cantidades por igual. No se aplica un límite automático de 24 toneladas.</div>';}
    if(wizardStep===2){body='<h2>Revisa antes de enviar</h2><p class="muted small">Puedes volver a cualquier paso para corregir los datos.</p><div class="review-box"><div class="review-header"><h3>Productos</h3>'+button('Editar','wizard-edit','0','text-button')+'</div>'+productTable(wizard)+'<div class="product-total"><span>Mercadería referencial</span><strong>'+USD(wizardTotal())+'</strong></div></div><div class="review-box" style="margin-top:18px"><div class="review-header"><h3>Entrega y responsable</h3>'+button('Editar','wizard-edit','1','text-button')+'</div><div class="summary-grid">'+[['Responsable',wizard.engineer],['Cliente',wizard.client],['Fecha requerida',DATE(wizard.requested)],['Destino',wizard.destination],['Embarques / PO',wizard.shipments+' / '+wizard.shipments],['Fábrica',state.products.find(p=>p.id===wizard.lines[0]?.product)?.factory]].map(([k,v])=>'<dl><dt>'+k+'</dt><dd>'+E(v)+'</dd></dl>').join('')+'</div></div><div class="info-box" style="margin-top:18px">Al enviar se asigna la PO, se crea su carpeta y se solicita aprobación. El correo a fábrica se genera después de completar ambas aprobaciones.</div>';}
    return head(wizard.revisionPO?'Corregir '+E(wizard.revisionPO):'Nueva solicitud','Del maestro de productos a una orden lista para aprobar.')+'<section class="panel wizard"><div class="steps">'+stepNames.map((n,i)=>'<div class="step '+(i===wizardStep?'active':i<wizardStep?'done':'')+'"><span class="step-number">'+(i<wizardStep?'✓':i+1)+'</span>'+n+'</div>').join('')+'</div><div class="wizard-body">'+(wizardError?'<div class="error" role="alert">'+E(wizardError)+'</div>':'')+body+'</div><div class="wizard-foot">'+button(wizardStep?'Anterior':'Cancelar',wizardStep?'wizard-back':'nav',wizardStep?'':'history')+button(wizardStep===2?'Enviar a aprobación':'Continuar',wizardStep===2?'wizard-submit':'wizard-next','','primary')+'</div></section>';
  }
  function approvalView(){const orders=state.orders.filter(p=>['Gerencia','Gerencia general'].includes(p.status));return head('Aprobaciones','Solicitudes pendientes de decisión y seguimiento del circuito.')+'<div class="info-box neutral">Circuito de demostración: Gerencia → Gerencia general. DA / NZ y su relación con este circuito deben confirmarse antes de la implementación.</div>'+(!orders.length?panel('Bandeja de aprobaciones',empty('No hay aprobaciones pendientes','Puedes crear una solicitud desde el menú.')):orders.map(p=>'<section class="approval-card"><div><h3>'+linkPO(p.id)+' '+pill(p.status)+'</h3><div class="small muted">'+E(p.engineer)+' · '+E(p.client)+' · '+DATE(p.requested)+'</div><div class="small" style="margin-top:8px">'+p.lines.length+' producto(s) · '+NUM(p.lines.reduce((n,l)=>n+l.qty,0))+' kg · '+USD(M.total(p))+'</div><div class="approval-steps">'+pill('1. Gerencia',p.approval[0]==='Aprobada'?'teal':'amber')+'<span>→</span>'+pill('2. Gerencia general',p.approval[1]==='Aprobada'?'teal':p.approval[0]==='Aprobada'?'amber':'')+'</div></div><div class="button-row">'+button('Revisar','po',p.id)+button('Rechazar','reject',p.id,'danger')+button('Simular aprobación','approve',p.id,'primary')+'</div></section>').join(''));
  }
  function emailFields(m){
    if(m.status!=='Procesado')return '';
    const f=M.parseBody(m.body),rows=[];
    if(m.report)Object.assign(f,{eta:m.report.eta,etd:m.report.etd,shipment:m.report.shipment});
    if(f.eta)rows.push(['ETA',DATE(f.eta),'Cuerpo del correo / informe de ejemplo']);
    if(f.etd)rows.push(['ETD',DATE(f.etd),'Cuerpo del correo / informe de ejemplo']);
    if(f.shipment)rows.push(['Embarque',f.shipment,'Cuerpo del correo / informe de ejemplo']);
    if(m.kind==='shipment')rows.push(['Cantidad',NUM(m.metadata.quantity)+' kg','Documento de ejemplo'],['Mercadería',USD(m.metadata.totalUSD),'Documento de ejemplo'],['Flete',USD(m.metadata.freightUSD),'Documento de ejemplo'],['Seguro',USD(m.metadata.insuranceUSD),'Documento de ejemplo']);
    if(m.kind==='liquidation')rows.push(['Gastos',CLP(m.metadata.customsCLP),'Liquidación de ejemplo'],['IVA informado',CLP(m.metadata.vatCLP),'Liquidación de ejemplo']);
    if(!rows.length)return '';
    return '<h3 style="margin-top:22px">Información incorporada</h3><div class="table-scroll"><table><thead><tr><th>CAMPO</th><th>VALOR</th><th>ORIGEN</th></tr></thead><tbody>'+rows.map(([k,v,source])=>'<tr><td>'+E(k)+'</td><td>'+E(v)+'</td><td class="muted small">'+E(source)+'</td></tr>').join('')+'</tbody></table></div>';
  }
  function emailView(){const m=state.emails.find(m=>m.id===selectedEmail)||state.emails[0];if(m)selectedEmail=m.id;return head('Correos procesados','Del correo al expediente: identificación, archivo y actualización.',button('＋ Simular correo entrante','receive-dialog','','primary'))+'<div class="info-box neutral">Los mensajes de esta bandeja son ejemplos. Se ejecuta su vinculación y clasificación en la demo; no hay conexión a un buzón ni extracción real de PDF.</div><div class="email-layout"><section class="panel email-list"><div class="panel-head"><h2>Bandeja de entrada</h2><span class="small muted">'+state.emails.length+' mensajes</span></div>'+state.emails.map(mail=>'<button class="email-item '+(mail.id===selectedEmail?'active':'')+'" data-action="email" data-id="'+E(mail.id)+'"><div class="email-top">'+pill(mail.status)+'<small>'+TIME(mail.received)+'</small></div><strong>'+E(mail.subject)+'</strong><small>'+E(mail.sender)+'</small></button>').join('')+'</section>'+(m?'<section class="panel"><div class="panel-head"><h2>Resultado del procesamiento</h2>'+pill(m.status)+'</div><div class="panel-body"><h3>'+E(m.subject)+'</h3><p class="small muted">De: '+E(m.sender)+' · Mensaje de ejemplo</p><pre class="email-body">'+E(m.body)+'</pre><h3>Archivos recibidos</h3>'+m.attachments.map(a=>'<span class="attachment">'+E(a)+'</span>').join('')+'<h3 style="margin-top:22px">Registro de automatización</h3><ul class="email-log">'+m.result.map(r=>'<li><span>'+ (m.status==='Procesado'?'✓':'!')+'</span>'+E(r)+'</li>').join('')+'</ul>'+emailFields(m)+(m.report?'<div class="info-box neutral" style="margin-top:18px">El informe de ejemplo actualizó ETA y ETD y registró un aviso del cambio. La política de actualización definitiva está por confirmar.</div>'+button('Descargar Excel de ejemplo','download-report',m.id):'')+'<div class="button-row" style="margin-top:20px">'+(m.poId?button('Abrir '+E(m.poId),'po',m.poId,'primary'):button('Resolver vinculación','resolve',m.id,'primary'))+'</div></div></section>':'')+'</div>';
  }
  function folderView(po){return M.folders.map(folder=>{const docs=po.docs.filter(d=>d.folder===folder);return '<div class="folder"><div class="folder-head"><span aria-hidden="true">▣</span>'+E(folder)+'<span>'+docs.length+' archivo(s)</span></div>'+docs.map(d=>'<div class="document-row"><div class="document-name"><span class="file-icon">PDF</span>'+E(d.name)+'<span class="cell-sub">'+E(d.type)+' · Versión '+d.version+' · '+E(d.source)+'</span></div><div class="button-row">'+button('Ver','doc-view',d.id,'text-button','data-po="'+po.id+'"')+button('Descargar','doc-download',d.id,'text-button','data-po="'+po.id+'"')+'</div></div>').join('')+(!docs.length?'<div class="folder-empty">Carpeta creada. Los archivos se incorporan al avanzar el proceso.</div>':'')+'</div>';}).join('');}
  function checks(po){return '<ul class="checklist">'+M.checklist(po).map(c=>'<li><span class="checkmark '+(c.done?'done':'')+'">'+(c.done?'✓':'–')+'</span>'+c.type+pill(c.done?'Recibido':'Pendiente',c.done?'teal':'amber')+'</li>').join('')+'</ul>';}
  function events(po){return '<ul class="timeline">'+po.events.map(ev=>'<li><strong>'+E(ev.title)+'</strong><p>'+E(ev.detail)+'</p><small>'+TIME(ev.at)+' · '+E(ev.source)+'</small></li>').join('')+'</ul>';}
  function agencyBody(po){const complete=M.checklist(po).every(d=>d.done),days=M.daysToETA(po);return '<div class="summary-grid" style="margin-bottom:20px"><dl><dt>ETA</dt><dd>'+DATE(po.eta)+'</dd></dl><dl><dt>Arribo</dt><dd>'+(days===null?'Por confirmar':days+' días desde la fecha de demo')+'</dd></dl><dl><dt>Responsable</dt><dd>'+E(po.engineer)+'</dd></dl></div>'+checks(po)+'<div class="info-box '+(complete?'':'amber')+'" style="margin-top:20px">'+(po.agencySent?'Paquete revisado y enviado a la agencia en la demostración.':complete?'Documentos completos. El ingeniero revisa y confirma el envío a AGA.':'El sistema identifica los documentos faltantes. La fábrica aporta los archivos; el ingeniero revisa el paquete.')+'</div><div class="button-row">'+button(po.agencySent?'Envío registrado':'Revisar envío a AGA','agency',po.id,'primary',!complete||po.agencySent?'disabled':'')+button('Ver carpetas','po',po.id,'secondary','data-tab="documents"')+'</div><p class="small muted" style="margin-top:15px">Alertas referenciales: faltantes a ETA −20 días; preparación del envío a ETA −15 días, con checklist completo y revisión del ingeniero.</p>';}
  function costBody(po){const base=M.total(po),hasFreight=po.costs.freightUSD!==null&&po.costs.insuranceUSD!==null;return '<div class="two-cols"><div><h3>Valores del embarque · USD</h3><div class="cost-row"><span>Mercadería<small>Maestro de producto de ejemplo</small></span><strong>'+USD(base)+'</strong></div><div class="cost-row"><span>Flete informado</span><strong>'+USD(po.costs.freightUSD)+'</strong></div><div class="cost-row"><span>Seguro informado</span><strong>'+USD(po.costs.insuranceUSD)+'</strong></div><div class="cost-row total"><span>Suma referencial USD</span><strong>'+ (hasFreight?USD(base+po.costs.freightUSD+po.costs.insuranceUSD):'Pendiente')+'</strong></div></div><div><h3>Gastos informados · CLP</h3><div class="cost-row"><span>Gastos de liquidación</span><strong>'+CLP(po.costs.customsCLP)+'</strong></div><div class="cost-row"><span>IVA informado</span><strong>'+CLP(po.costs.vatCLP)+'</strong></div><div class="cost-row"><span>Transporte terrestre</span><strong>'+CLP(po.transport?.cost)+'</strong></div></div></div><div class="info-box neutral" style="margin-top:22px">Importes ficticios para mostrar el registro y la consulta. No se calcula un DDP definitivo ni se suman monedas distintas. Reglas aduaneras, tipo de cambio y reparto por producto pendientes de definición.</div><h3>Referencia manual en MANAGER</h3><div class="button-row"><input id="managerRef" aria-label="Referencia de registro manual en MANAGER" placeholder="Referencia del registro manual" maxlength="80" value="'+E(po.manager)+'">'+button('Guardar referencia','manager',po.id)+'</div><p class="small muted" style="margin-top:12px">MANAGER permanece manual. Este campo solo deja constancia del registro en la demo.</p>';}
  function transportBody(po){return po.transport?'<div class="summary-grid">'+[['Orden',po.transport.id],['Transportista',po.transport.company],['Fecha',DATE(po.transport.date)],['Destino',po.transport.destination],['Importe CLP',CLP(po.transport.cost)],['Correo','Envío simulado registrado']].map(([k,v])=>'<dl><dt>'+k+'</dt><dd>'+E(v)+'</dd></dl>').join('')+'</div><div class="button-row" style="margin-top:22px">'+button('Ver OT','doc-view',po.docs.find(d=>d.type==='OT Transporte')?.id,'primary','data-po="'+po.id+'"')+'</div>':'<div class="info-box neutral">La OT se prepara desde el expediente. El evento de emisión y el responsable definitivo deben validarse con la jefa.</div>'+button('Preparar OT de transporte','ot',po.id,'primary',!po.agencySent?'disabled':'')+(!po.agencySent?'<p class="small muted" style="margin-top:12px">En esta demo se habilita después del envío a AGA.</p>':'');}
  function detailView(){const po=poById(selectedPO);if(!po)return head('PO no encontrada')+empty('No existe en esta sesión','Vuelve al historial de PO.');const tabs=[['overview','Resumen'],['request','Solicitud'],['factory','Fábrica'],['customs','Aduanas'],['transport','Transporte'],['costs','Costos'],['documents','Documentos'],['events','Historial']];let body='';
    if(tab==='overview')body='<div class="two-cols"><div>'+panel('Productos solicitados',productTable(po))+panel('Actividad reciente',events({...po,events:po.events.slice(0,5)}),button('Ver historial','po',po.id,'text-button','data-tab="events"'))+'</div><div>'+panel('Datos del expediente','<div class="summary-grid">'+[['Cliente',po.client],['Destino',po.destination],['Responsable',po.engineer],['Fábrica',po.factory],['Embarque',po.shipment||'Por confirmar'],['Revisión',po.revision]].map(([k,v])=>'<dl><dt>'+k+'</dt><dd>'+E(v)+'</dd></dl>').join('')+'</div>')+panel('Documentos de embarque',checks(po),button('Abrir carpetas','po',po.id,'text-button','data-tab="documents"'))+'</div></div>';
    if(tab==='request')body=panel('Solicitud y aprobaciones',productTable(po)+'<div class="approval-steps" style="margin:22px 0">'+pill('Gerencia: '+(po.approval[0]||'Pendiente'),po.approval[0]==='Aprobada'?'teal':'amber')+pill('Gerencia general: '+(po.approval[1]||'Pendiente'),po.approval[1]==='Aprobada'?'teal':'amber')+'</div>'+(po.status==='Rechazada'?'<div class="error">Motivo: '+E(po.rejection)+'</div>'+button('Corregir y reenviar','revise',po.id,'primary'):['Gerencia','Gerencia general'].includes(po.status)?'<div class="button-row">'+button('Rechazar','reject',po.id,'danger')+button('Simular aprobación de '+E(po.status),'approve',po.id,'primary')+'</div>':'<div class="info-box">Solicitud aprobada. PDF referencial y correo a fábrica registrados.</div>')+'<p class="small muted" style="margin-top:20px">Formato de solicitud a fábrica y circuito definitivo pendientes de validación. Los números DEMO no corresponden al correlativo real de la empresa.</p>');
    if(tab==='factory')body=panel('Seguimiento de fábrica','<div class="summary-grid">'+[['Estado',po.stock||'A la espera de confirmación'],['ETD',DATE(po.etd)],['ETA',DATE(po.eta)],['Embarque',po.shipment||'Por confirmar'],['Último correo',state.emails.find(m=>m.poId===po.id)?.subject||'Sin correos de ejemplo'],['Archivos de fábrica',po.docs.filter(d=>d.folder===M.folders[1]).length]].map(([k,v])=>'<dl><dt>'+k+'</dt><dd>'+E(v)+'</dd></dl>').join('')+'</div><div class="button-row" style="margin-top:24px">'+button('Simular correo de fábrica','receive-dialog',po.id,'primary',M.stages.indexOf(po.status)<2?'disabled':'')+button('Abrir bandeja','nav','emails')+'</div><div class="info-box neutral" style="margin-top:20px">Los correos e informes de ejemplo alimentan este registro. Los cambios quedan en el historial y generan un aviso de demostración.</div>');
    if(tab==='customs')body=panel('Preparación documental para AGA',agencyBody(po));
    if(tab==='transport')body=panel('Transporte terrestre',transportBody(po));
    if(tab==='costs')body=panel('Costos y referencia MANAGER',costBody(po));
    if(tab==='documents')body=panel('Carpeta '+E(po.id),folderView(po),button('Descargar expediente ZIP','zip',po.id,'text-button'));
    if(tab==='events')body=panel('Historial del expediente',events(po),button('Exportar expediente JSON','export-po',po.id,'text-button'));
    const phase=po.status==='Rechazada'?0:M.stages.indexOf(po.status);const grouped=phase<=1?0:phase===2?1:phase===3?2:phase===4?3:phase===5?4:5;
    return '<div class="detail-head"><div>'+button('Volver al historial','nav','history','back-link')+'<div class="detail-title"><h1>'+E(po.id)+'</h1>'+pill(po.status)+'</div><div class="detail-meta">'+E(po.client)+' · '+E(po.engineer)+' · Revisión '+po.revision+'</div></div><div class="button-row">'+button('Simular correo entrante','receive-dialog',po.id,'secondary',phase<2?'disabled':'')+button('Exportar ficha','export-po',po.id,'secondary')+'</div></div><section class="panel"><div class="journey">'+['Aprobación','Envío a fábrica','Preparación','Embarque','Aduanas','Transporte'].map((s,i)=>'<div class="journey-step '+(i<grouped?'past':i===grouped?'current':'')+'"><span class="journey-dot">'+(i<grouped?'✓':i+1)+'</span>'+s+'</div>').join('')+'</div><div class="metric-strip"><div><small>Mercadería USD</small><strong>'+USD(M.total(po))+'</strong></div><div><small>Fecha requerida</small><strong>'+DATE(po.requested)+'</strong></div><div><small>ETD</small><strong>'+DATE(po.etd)+'</strong></div><div><small>ETA</small><strong>'+DATE(po.eta)+'</strong></div></div><div class="tabs" role="tablist" aria-label="Secciones de la PO">'+tabs.map(([key,label])=>'<button role="tab" aria-selected="'+(tab===key)+'" class="tab '+(tab===key?'active':'')+'" data-action="tab" data-id="'+key+'">'+label+'</button>').join('')+'</div></section>'+body;
  }
  function factoryView(){const orders=state.orders.filter(p=>M.stages.indexOf(p.status)>=2&&p.status!=='Finalizada');return head('Fábrica','Confirmaciones, fechas e información recibida por embarque.',button('Simular correo entrante','receive-dialog','','primary'))+'<div class="cards">'+orders.map(p=>'<section class="panel module-card"><div class="module-card-header"><div><h2>'+linkPO(p.id)+'</h2><p>'+E(p.factory)+' · '+E(p.engineer)+'</p></div>'+pill(p.status)+'</div><div class="summary-grid">'+[['ETD',DATE(p.etd)],['ETA',DATE(p.eta)],['Embarque',p.shipment||'Por confirmar'],['Documentos',p.docs.filter(d=>d.folder===M.folders[1]).length+' recibidos']].map(([k,v])=>'<dl><dt>'+k+'</dt><dd>'+E(v)+'</dd></dl>').join('')+'</div><div class="button-row">'+button('Abrir seguimiento','po',p.id,'secondary','data-tab="factory"')+button('Simular correo','receive-dialog',p.id,'text-button')+'</div></section>').join('')+'</div>';}
  function customsView(){const orders=state.orders.filter(p=>M.stages.indexOf(p.status)>=4&&p.status!=='Finalizada');return head('Aduanas','Documentos recibidos, faltantes y revisión del paquete para AGA.')+'<div class="info-box neutral">Los documentos provienen de los correos. El ingeniero revisa el paquete preparado antes de confirmar su envío.</div><div class="cards">'+orders.map(p=>'<section class="panel module-card"><div class="module-card-header"><div><h2>'+linkPO(p.id)+'</h2><p>'+E(p.engineer)+' · ETA '+DATE(p.eta)+'</p></div>'+pill(p.agencySent?'Envío registrado':M.checklist(p).every(x=>x.done)?'Listo para revisar':'Faltan documentos',p.agencySent?'teal':'amber')+'</div>'+checks(p)+'<div class="button-row">'+button('Abrir Aduanas','po',p.id,'secondary','data-tab="customs"')+button('Revisar envío','agency',p.id,'primary',p.agencySent||M.checklist(p).some(x=>!x.done)?'disabled':'')+'</div></section>').join('')+'</div>';}
  function transportView(){const orders=state.orders.filter(p=>p.agencySent);return head('Transporte','Órdenes de transporte relacionadas con cada expediente.')+'<div class="info-box neutral">Emisión y responsables de OT pendientes de validación. Bodega está fuera de esta demostración.</div><div class="cards">'+orders.map(p=>'<section class="panel module-card"><div class="module-card-header"><div><h2>'+linkPO(p.id)+'</h2><p>'+E(p.client)+' · '+E(p.destination)+'</p></div>'+pill(p.transport?'OT emitida':'Por preparar',p.transport?'teal':'amber')+'</div>'+transportBody(p)+'<div class="button-row">'+button('Abrir Transporte','po',p.id,'text-button','data-tab="transport"')+'</div></section>').join('')+'</div>';}
  function costView(){return head('Costos','Valores informados por PO, con monedas y fuentes diferenciadas.')+'<div class="info-box neutral">El costo DDP definitivo y el reparto por producto se definirán con la empresa. MANAGER se registra manualmente.</div><section class="panel"><div class="table-scroll"><table><thead><tr><th>PO</th><th>MERCADERÍA USD</th><th>FLETE USD</th><th>SEGURO USD</th><th>LIQUIDACIÓN CLP</th><th>TRANSPORTE CLP</th><th>MANAGER</th><th></th></tr></thead><tbody>'+state.orders.map(p=>'<tr><td>'+linkPO(p.id)+'</td><td>'+USD(M.total(p))+'</td><td>'+USD(p.costs.freightUSD)+'</td><td>'+USD(p.costs.insuranceUSD)+'</td><td>'+CLP(p.costs.customsCLP)+'</td><td>'+CLP(p.transport?.cost)+'</td><td>'+E(p.manager||'Sin referencia')+'</td><td>'+button('Ver costos','po',p.id,'text-button','data-tab="costs"')+'</td></tr>').join('')+'</tbody></table></div></section>';}
  function masterView(){return head('Maestros','Productos y precios que completan automáticamente la solicitud.')+'<div class="info-box neutral">Maestros ficticios. Editar un precio deja el producto pendiente de aprobación para nuevas solicitudes; las PO existentes conservan el precio que tenían al crearse.</div><section class="panel"><div class="table-scroll"><table><thead><tr><th>PRODUCTO</th><th>FORMA</th><th>FÁBRICA</th><th>PRECIO USD / KG</th><th>ESTADO</th><th></th></tr></thead><tbody>'+state.products.map(p=>'<tr><td><strong>'+E(p.name)+'</strong><span class="cell-sub">'+p.id+'</span></td><td>'+p.form+'</td><td>'+E(p.factory)+'</td><td>'+USD(p.price)+'</td><td>'+pill(p.approved?'Aprobado':'Pendiente',p.approved?'teal':'amber')+'</td><td><div class="button-row">'+button('Editar precio','master-edit',p.id,'text-button')+(!p.approved?button('Simular aprobación','master-approve',p.id,'text-button'):'')+'</div></td></tr>').join('')+'</tbody></table></div></section>';}
  function alertView(){const alerts=M.alerts(state);return head('Alertas','Pendientes derivados del estado y la información del expediente.')+'<div class="info-box neutral">Fecha de referencia de la demo: 3 de octubre de 2026. Las notificaciones y los envíos programados se muestran como ejemplos; no hay tareas ejecutándose en segundo plano.</div><section class="panel">'+alerts.map(a=>'<div class="alert-row"><div>'+pill(a.type,a.type==='Correo'?'red':'amber')+' <small>'+E(a.po)+'</small><p>'+E(a.text)+'</p></div>'+button('Revisar',a.po.startsWith('DEMO-')?'po':'nav',a.po.startsWith('DEMO-')?a.po:a.route,'text-button','data-tab="'+(a.route==='customs'?'customs':a.route==='costs'?'costs':'request')+'"')+'</div>').join('')+(!alerts.length?empty('Sin alertas pendientes','Los expedientes de esta sesión están al día.'):'')+'</section>';}
  function receiveDialog(id){const orders=state.orders.filter(p=>M.stages.indexOf(p.status)>=2&&p.status!=='Finalizada');if(!orders.length){showDialog('Primero envía una PO a fábrica','<p>Crea una solicitud y completa las dos aprobaciones de demostración.</p>',button('Ir a aprobaciones','nav-close','approvals','primary'));return;}
    showDialog('Simular correo entrante','<div class="info-box neutral">Este ejemplo permite seguir el procesamiento de un mensaje. No lee un correo real ni ejecuta OCR.</div><div class="field"><label for="mailPO">PO de destino</label><select id="mailPO">'+orders.map(p=>'<option value="'+p.id+'" '+(p.id===id?'selected':'')+'>'+p.id+' · '+p.status+'</option>').join('')+'</select></div><div class="field"><label for="mailKind">Mensaje de ejemplo</label><select id="mailKind"><option value="confirmation">1. Confirmación · stock, ETA y ETD</option><option value="shipment">2. Embarque · Invoice, Packing List y BL</option><option value="certificate">3. Certificado de origen · completar checklist</option><option value="weekly">4. Informe semanal · cambio de fechas</option><option value="liquidation">5. Liquidación de aduana · valores informados</option><option value="unknown">Excepción · número de PO sin coincidencia</option></select></div><p class="small muted">Los nombres de archivo son ficticios. La regla real de clasificación debe validarse con ejemplos de cada fábrica.</p>',button('Cancelar','close')+button('Procesar correo de ejemplo','receive-confirm','','primary'));
  }
  function docFor(po,id){return po?.docs.find(d=>d.id===id);}
  function ascii(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,' ').replace(/[\\()]/g,c=>'\\'+c);}
  function pdfBytes(lines){const text=['BT','/F1 11 Tf','48 792 Td',...lines.slice(0,49).flatMap((line,i)=>[(i?'0 -15 Td':''),'('+ascii(line)+') Tj']),'ET'].filter(Boolean).join('\n');const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length '+text.length+' >>\nstream\n'+text+'\nendstream'];let out='%PDF-1.4\n',offsets=[0];objs.forEach((o,i)=>{offsets.push(out.length);out+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=out.length;out+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return new Blob([out],{type:'application/pdf'});}
  function documentPDF(po,doc){return pdfBytes(['COMEX - DOCUMENTO DE DEMOSTRACION','DATOS FICTICIOS - SIN VALIDEZ COMERCIAL',doc.type+' - '+po.id,'Formato referencial pendiente de validacion.','', 'PO: '+po.id+' | Revision: '+po.revision,'Cliente: '+po.client,'Responsable: '+po.engineer,'Fabrica: '+po.factory,'Destino: '+po.destination,'Embarque: '+(po.shipment||'Por confirmar'),'ETA: '+(po.eta||'Por confirmar')+' | ETD: '+(po.etd||'Por confirmar'),'','Productos:',...po.lines.map(l=>l.name+' | '+l.qty+' kg | USD/kg '+l.price+' | USD '+(l.qty*l.price).toFixed(2)),'Total mercaderia USD: '+M.total(po).toFixed(2),'', 'Tipo de archivo: '+doc.type,'Nombre: '+doc.name,'Carpeta: '+po.id+'/'+doc.folder,'Origen de ejemplo: '+doc.source,...(doc.type==='OT Transporte'&&po.transport?['OT: '+po.transport.id,'Transportista: '+po.transport.company,'Fecha: '+po.transport.date,'Importe CLP: '+po.transport.cost]:[]),'','Esta demostracion no envia correos ni extrae informacion de PDF reales.']);}
  function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
  async function downloadZip(po){if(!window.JSZip)throw Error('No se pudo cargar el generador de ZIP.');const zip=new JSZip();M.folders.forEach(f=>zip.folder(po.id+'/'+f));po.docs.forEach(d=>zip.file(po.id+'/'+d.folder+'/'+d.name,documentPDF(po,d)));zip.file(po.id+'/ficha.json',JSON.stringify(po,null,2));download(await zip.generateAsync({type:'blob'}),po.id+'_expediente.zip');toast('Expediente de demostración descargado.');}
  async function downloadReport(mail){const rows=[['PO','ETA','ETD','Estado'],...[...(mail.report?.rows||[])].map(r=>[r.po,r.eta,r.etd,r.status])];const xml='<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((row,i)=>'<row r="'+(i+1)+'">'+row.map((v,j)=>'<c r="'+String.fromCharCode(65+j)+(i+1)+'" t="inlineStr"><is><t>'+E(v)+'</t></is></c>').join('')+'</row>').join('')+'</sheetData></worksheet>';const z=new JSZip();z.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');z.file('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');z.file('xl/workbook.xml','<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Informe de ejemplo" sheetId="1" r:id="rId1"/></sheets></workbook>');z.file('xl/_rels/workbook.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');z.file('xl/worksheets/sheet1.xml',xml);download(await z.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'REPORTE_SEMANAL_'+mail.poId+'.xlsx');}
  function modalError(error){const body=document.querySelector('.modal-content');body.querySelector('.error')?.remove();const el=document.createElement('div');el.className='error';el.setAttribute('role','alert');el.textContent=error.message||String(error);body.prepend(el);}
  async function act(action,id,el){
    if(action==='close'){close();return;}
    if(action==='nav'||action==='nav-close'){if(action==='nav-close')close();go(id);return;}
    if(action==='po'){go('po',id,el.dataset.tab||'overview');return;}
    if(action==='tab'){go('po',selectedPO,id);return;}
    if(action==='alerts'){go('alerts');return;}
    if(action==='new'){initWizard();go('request');render();return;}
    if(action==='guide'){showDialog('Recorrido para presentar','<ol><li><strong>Nueva solicitud:</strong> selecciona productos, completa la entrega y revisa el resumen.</li><li><strong>Aprobaciones:</strong> simula primero Gerencia y luego Gerencia general. Se genera el PDF y el envío de ejemplo.</li><li><strong>Correos procesados:</strong> simula confirmación, documentos de embarque y certificado de origen para la nueva PO.</li><li><strong>Expediente:</strong> revisa fechas, carpetas, checklist e historial actualizados.</li><li><strong>Aduanas:</strong> verifica el paquete y confirma el envío de demostración a AGA.</li><li><strong>Transporte:</strong> prepara y emite una OT de ejemplo.</li></ol><div class="info-box neutral">La demo muestra el flujo y ejecuta cambios entre pantallas. Las conexiones reales a correo, almacenamiento e IA están pendientes.</div>',button('Cerrar','close')+button('Crear una solicitud','guide-start','','primary'));return;}
    if(action==='guide-start'){close();initWizard();go('request');render();return;}
    if(action==='limitations'){showDialog('Alcance de esta demostración','<p>Prototipo con datos ficticios y estado temporal en esta pestaña.</p><ul><li>Solicitudes por pasos, PO de ejemplo y aprobaciones consecutivas.</li><li>Procesamiento de mensajes de ejemplo y clasificación por nombre de archivo.</li><li>Documentos PDF referenciales, carpetas, checklist y registro de cambios.</li><li>Revisión y envío simulado a AGA; OT de transporte referencial.</li></ul><p class="small muted">La conexión real al correo y almacenamiento, extracción de PDF, seguridad corporativa y reglas definitivas de costeo se implementarán en el sistema operativo. Los perfiles y formatos están pendientes de validación. Bodega no está incluida.</p>');return;}
    if(action.startsWith('wizard-')||action==='add-line'||action==='remove-line'){
      collectWizard();wizardError='';
      if(action==='wizard-next'){if(wizardStep===0){M.validateRequest(state,wizard);}else M.validateRequest(state,wizard);wizardStep=Math.min(2,wizardStep+1);}
      if(action==='wizard-back')wizardStep=Math.max(0,wizardStep-1);
      if(action==='wizard-edit')wizardStep=Number(id);
      if(action==='add-line'){const p=state.products.find(p=>p.approved&&!wizard.lines.some(l=>l.product===p.id)&&p.factory===state.products.find(x=>x.id===wizard.lines[0]?.product)?.factory);if(!p)throw Error('No hay otro producto aprobado de esta fábrica en el maestro de ejemplo.');wizard.lines.push({product:p.id,qty:1000});}
      if(action==='remove-line'&&wizard.lines.length>1)wizard.lines.splice(Number(id),1);
      if(action==='wizard-submit')successOrders=wizard.revisionPO?M.revise(state,wizard.revisionPO,wizard):M.createOrders(state,wizard);
      render();return;
    }
    if(action==='approve'){const po=poById(id);showDialog('Aprobación de '+E(po.status),'<p>Solicitud <strong>'+E(id)+'</strong> de '+E(po.engineer)+'.</p>'+productTable(po)+'<p class="small muted" style="margin-top:18px">'+(po.status==='Gerencia'?'Esta decisión habilita la revisión de Gerencia general.':'Esta decisión completa el circuito, genera el PDF referencial y registra el correo de salida a fábrica.')+'</p><div class="info-box neutral">Aprobación simulada. No representa una firma o autorización real.</div>',button('Cancelar','close')+button('Confirmar aprobación de prueba','approve-confirm',id,'primary'));return;}
    if(action==='approve-confirm'){const po=M.decide(state,id,'approve');close();render();toast(po.status==='Enviada a fábrica'?'Aprobada: PDF y correo a fábrica generados en la demo.':'Aprobada por Gerencia. Pendiente Gerencia general.');return;}
    if(action==='reject'){showDialog('Rechazar solicitud '+E(id),'<label for="rejectReason">Observaciones para el ingeniero</label><textarea id="rejectReason" maxlength="500" placeholder="Indica qué debe corregir"></textarea>',button('Cancelar','close')+button('Confirmar rechazo','reject-confirm',id,'danger'));return;}
    if(action==='reject-confirm'){M.decide(state,id,'reject',document.getElementById('rejectReason').value);close();render();toast('Rechazo registrado e ingeniero notificado en la demo.');return;}
    if(action==='revise'){initWizard(poById(id));go('request');render();return;}
    if(action==='email'){selectedEmail=id;render();return;}
    if(action==='receive-dialog'){receiveDialog(id);return;}
    if(action==='receive-confirm'){const mail=M.receive(state,document.getElementById('mailPO').value,document.getElementById('mailKind').value);close();if(mail.id)selectedEmail=mail.id;go('emails');render();toast(mail.duplicate?'Reenvío detectado: no se duplicó información.':mail.status==='Por vincular'?'Correo por vincular: COMEX debe identificar la PO.':'Correo de ejemplo procesado y expediente actualizado.');return;}
    if(action==='resolve'){const mail=state.emails.find(m=>m.id===id),orders=state.orders.filter(p=>M.stages.indexOf(p.status)>=2&&p.status!=='Finalizada');showDialog('Resolver vinculación','<p class="small">'+E(mail.subject)+'</p><div class="field"><label for="resolvePO">PO correcta, verificada por COMEX</label><select id="resolvePO">'+orders.map(p=>'<option value="'+p.id+'">'+p.id+' · '+E(p.client)+'</option>').join('')+'</select></div><div class="info-box neutral">Se registra la corrección y se conserva el nombre del archivo recibido.</div>',button('Cancelar','close')+button('Vincular y procesar','resolve-confirm',id,'primary'));return;}
    if(action==='resolve-confirm'){M.process(state,state.emails.find(m=>m.id===id),document.getElementById('resolvePO').value);close();render();toast('Vinculación registrada y correo procesado.');return;}
    if(action==='agency'){const po=poById(id);if(M.checklist(po).some(c=>!c.done))throw Error('Faltan documentos obligatorios para preparar el envío.');showDialog('Revisión de documentos para AGA','<p><strong>'+E(id)+'</strong> · '+E(po.engineer)+'</p>'+checks(po)+'<p class="small muted" style="margin-top:18px">Destinatario de ejemplo: operaciones@agencia.example</p><label class="checkbox-label"><input type="checkbox" id="agencyReviewed"><span>Revisé que los documentos y la PO corresponden al embarque.</span></label>',button('Cancelar','close')+button('Confirmar envío de prueba','agency-confirm',id,'primary'));return;}
    if(action==='agency-confirm'){M.sendAgency(state,id,document.getElementById('agencyReviewed').checked);close();render();toast('Paquete revisado. Envío a AGA registrado en la demo.');return;}
    if(action==='ot'){const po=poById(id);showDialog('Preparar OT de transporte','<p class="small muted">'+E(id)+' · Datos de demostración; formato y responsable por validar.</p><div class="field-grid"><div class="field"><label for="otCompany">Transportista</label><input id="otCompany" value="Transportista · ejemplo" maxlength="120"></div><div class="field"><label for="otDate">Fecha de transporte</label><input type="date" id="otDate" value="'+E(po.eta||'2026-11-03')+'"></div><div class="field wide"><label for="otDestination">Destino</label><input id="otDestination" value="'+E(po.destination)+'" maxlength="200"></div><div class="field"><label for="otCost">Importe referencial CLP</label><input type="number" min="1" id="otCost" value="583100"></div></div>',button('Cancelar','close')+button('Emitir OT de prueba','ot-confirm',id,'primary'));return;}
    if(action==='ot-confirm'){M.emitOT(state,id,{company:document.getElementById('otCompany').value,date:document.getElementById('otDate').value,destination:document.getElementById('otDestination').value,cost:Number(document.getElementById('otCost').value)});close();render();toast('OT y envío al transportista generados en la demo.');return;}
    if(action==='manager'){const po=poById(id),ref=document.getElementById('managerRef').value.trim();if(!ref)throw Error('Ingresa la referencia del registro manual.');po.manager=ref;M.log(po,'Referencia MANAGER registrada',ref+' · registro manual de demostración.');render();toast('Referencia manual guardada en esta sesión.');return;}
    if(action==='master-edit'){const p=state.products.find(p=>p.id===id);showDialog('Editar precio de '+E(p.name),'<div class="field"><label for="masterPrice">Precio referencial USD / kg</label><input type="number" step="0.01" min="0.01" id="masterPrice" value="'+p.price+'"></div><p class="small muted">El cambio requerirá una nueva aprobación del maestro para crear solicitudes.</p>',button('Cancelar','close')+button('Guardar cambio','master-save',id,'primary'));return;}
    if(action==='master-save'){const p=state.products.find(p=>p.id===id),value=Number(document.getElementById('masterPrice').value);if(!Number.isFinite(value)||value<=0||value>1000000)throw Error('Ingresa un precio positivo válido.');p.price=value;p.approved=false;close();render();toast('Precio actualizado. Maestro pendiente de aprobación.');return;}
    if(action==='master-approve'){state.products.find(p=>p.id===id).approved=true;render();toast('Maestro aprobado en la demostración.');return;}
    if(action==='doc-view'||action==='doc-download'){const po=poById(el.dataset.po),d=docFor(po,id);if(!d)throw Error('Documento no encontrado.');const blob=documentPDF(po,d);if(action==='doc-download'){download(blob,d.name);return;}const url=URL.createObjectURL(blob);showDialog('Documento de ejemplo','<p class="small muted">'+E(d.name)+' · PDF ficticio, sin validez comercial.</p><iframe title="Vista previa de PDF de demostración" src="'+url+'" style="width:100%;height:440px;border:1px solid #dfe6ec;border-radius:6px"></iframe>',button('Cerrar','close')+button('Descargar PDF','doc-download',id,'primary','data-po="'+po.id+'"'));modal.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});return;}
    if(action==='zip'){await downloadZip(poById(id));return;}
    if(action==='download-report'){await downloadReport(state.emails.find(m=>m.id===id));return;}
    if(action==='export-po'){download(new Blob([JSON.stringify(poById(id),null,2)],{type:'application/json'}),id+'_ficha.json');return;}
    if(action==='export-history'){const clean=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const rows=[['PO','Responsable','Cliente','Estado','ETA','ETD','Mercaderia USD'],...state.orders.map(p=>[p.id,p.engineer,p.client,p.status,p.eta||'',p.etd||'',M.total(p)])];download(new Blob(['\ufeff'+rows.map(r=>r.map(clean).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'COMEX_historial_demo.csv');return;}
  }
  document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;try{await act(el.dataset.action,el.dataset.id||'',el);}catch(error){if(modal.open)modalError(error);else if(route==='request'){wizardError=error.message;render();}else toast(error.message);}});
  document.addEventListener('input',event=>{if(event.target.id==='historySearch'){q=event.target.value;document.getElementById('historyTable').innerHTML=historyRows();}});
  document.addEventListener('change',event=>{if(event.target.id==='statusFilter'){statusFilter=event.target.value;document.getElementById('historyTable').innerHTML=historyRows();}if(event.target.matches('[data-line-product],[data-line-qty],[data-wfield]')){collectWizard();if(event.target.matches('[data-line-product],[data-line-qty]'))render();}});
  document.getElementById('menuToggle').addEventListener('click',()=>{const open=document.getElementById('sidebar').classList.toggle('open');document.getElementById('menuToggle').setAttribute('aria-expanded',String(open));});
  window.addEventListener('hashchange',routeChanged);
  modal.addEventListener('click',event=>{if(event.target===modal){const r=modal.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();}});
  window.COMEXDemo={snapshot:()=>JSON.parse(JSON.stringify(state)),version:'2026-10-03.2'};
  routeChanged();
})();
